"""add soft delete at chat services

Revision ID: 16c717ffbb81
Revises: cdbc1cbf02e6
Create Date: 2026-05-06 13:46:22.467838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c717ffbb81'
down_revision: Union[str, Sequence[str], None] = 'cdbc1cbf02e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_chat_messages_deleted_at'), 'chat_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_is_deleted'), 'chat_messages', ['is_deleted'], unique=False)
    op.add_column('chat_sessions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_deleted_at'), 'chat_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_is_deleted'), 'chat_sessions', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_is_deleted'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_deleted_at'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'deleted_at')
    op.drop_column('chat_sessions', 'is_deleted')
    op.drop_index(op.f('ix_chat_messages_is_deleted'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_deleted_at'), table_name='chat_messages')
    op.drop_column('chat_messages', 'deleted_at')
    op.drop_column('chat_messages', 'is_deleted')
    # ### end Alembic commands ###
